plugins {
    id 'com.android.application'
}

android {
    namespace 'com.biscuit.iphone'
    compileSdk 35

    defaultConfig {
        applicationId "com.biscuit.iphone"
        minSdk 27
        targetSdk 28
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.15.0'
}
