plugins {
    id 'com.android.application'
}

android {
    namespace 'com.biscuit.launcher'
    compileSdk 34

    defaultConfig {
        applicationId 'com.biscuit.launcher'
        minSdk 27
        targetSdk 27
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'
            ), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_8
        targetCompatibility JavaVersion.VERSION_8
    }
}
